name: "Seaweed Sandwich"
description: "Playing by the sea"


# github
baseurl: "/seaweedsandwich/"
url: http://elliz.github.io/seaweedsandwich/

# live
# baseurl: "/"
# url: http://www.greenshoots.co.uk/

relative_permalinks: false
permalink: /:categories/:title
highlighter: rouge

future: false 

markdown: kramdown

gems:
- jekyll-sitemap
- jekyll-feed


# Photos collection in portfolio folder

#collections:
#  images:
#    output: true
#    permalink: /portfolio/:path/


compress_html:
  clippings: []
  comments: []
  endings: []
  profile: false
  ignore:
    envs: []
